name: Create Issue Every Week

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create an issue
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/issues
          title: Scheduled Issue - ${{ github.event.inputs.issue_title || github.run_id }}
          body: This is an automatically created issue every week @hoaongtrieu9.
        env:
          GITHUB_TOKE: ${{ secrets.GITHUB_TOKEN }}
