name: Create Issue Every 12 Hours

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create an issue
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/issues
          title: Scheduled Issue - ${{ github.event.inputs.issue_title || github.run_id }}
          body: This is an automatically created issue every 12 hours @hoaongtrieu9.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
